### PR TITLE
Use .deb libtool instead of savannah version

### PR DESCRIPTION
**Pull request by sergio-costas**
This is to avoid the downloading problems we are having from the Savannah git repo from GNU.

### CODE REVIEW

**Comment by 3v1n0** [comment]
I feel we can just remove the commented code, I feel this is one of those components that taking from the distro is just better than compiling it again in the sdk, being it quite core anyways

**Review by seb128 — CHANGES_REQUESTED** [review]
I agree with Marco there, let's just use the deb going forward

**Comment by sergio-costas** [comment]
@seb128 @3v1n0 Commented code removed. Also found that it is using an old .deb for mozjs... preparing a new patch.

**Comment by 3v1n0** [comment]
Thanks, squash the two commits please though.

**Comment by sergio-costas** [comment]
Squashed

**Review by seb128 — APPROVED** [review]
Thanks

**Pull request merged**
