### PR TITLE
Sdk indicator cleanup

### PR DESCRIPTION
**Pull request by kenvandine**

### CODE REVIEW

**Review by sergio-costas — DISMISSED** [review]
LGTM

**Comment by sergio-costas** [comment]
Mmm... wait... in my system, if I try to install libappindicator3-dev, it says that there is a conflict with libayatana-appindicator3. So I think that we should choose which one to install: or libappindicator3-dev, or libayatana-appindicator3-dev, but it seems that it is not possible to install both.

**Comment by sergio-costas** [comment]
Ok, I built the sdk with this patch and it included both libraries, which means that programs linked against libappindicator will use it, and programs linked against libayatana-appindicator will use it, no matter that libayatana-appindicator is compatible with libappindicator.

Should we remove the libappindicator?

**Comment by kenvandine** [comment]
Yeah, I think we should remove it

**Pull request merged**
