### PR TITLE
allow ci reruns and update upload artifact action

### PR DESCRIPTION
**Pull request by jssotomdz**

### CODE REVIEW

**Comment by jssotomdz** [comment]
@sergio-costas @seb128 should I commit the v4 change directly into the rest of the repos? to avoid spamming and creating >20 pull requests

**Review by sergio-costas — APPROVED** [review]
I don't know about the "workflow_dispatch:" entry, but the version change is exactly what it has to be done to fix it.

**Comment by sergio-costas** [comment]
@jssotomdz In my opinion, yes, you should do that. It's a sensible change.

**Review by seb128 — APPROVED** [review]
> I don't know about the "workflow_dispatch:" entry, but the version change is exactly what it has to be done to fix it.

The  workflow_dispatch gives you the ability to trigger the job manually

The changes makes sense to me, thanks!

**Comment by sergio-costas** [comment]
@seb128 Oh, good to know. Thanks!

**Pull request merged**
