### PR TITLE
Don't delete index.theme files in icons folder

### PR DESCRIPTION
**Pull request by sergio-costas**
The index.theme file is required to regenerate the icon cache, so it must be preserved when checking for duplicated files.

This patch does this, thus allowing to regenerate the icons cache after duplicates have been removed, thus ensuring that only really-available icons will be added to the cache.

### CODE REVIEW

**Comment by seb128** [comment]
Could you give a bit more details in the impact? Is there any user visible issue in one of our snaps created by that code today?

**Comment by sergio-costas** [comment]
Not in any current, but I'm working on using gnome-46 as a base snap for ubuntu-desktop-session.snap, and I'm worried that the lack of it can have impact. It is true that the index-theme.cache files are still there, but... well... for completeness.

**Comment by sergio-costas** [comment]
Oh... also, I'm recreating the cache AFTER removing the duplicated icons. This is how it should be done. And that's why I must preserve the index.theme file. Without it, it's not possible to recreate it.

**Comment by sergio-costas** [comment]
Maybe I should modify the title...

**Review by seb128 — APPROVED** [review]
Ok, that seems to make sense indeed!

**Pull request merged**
