### PR TITLE
snap: rely on gpu-2404 providers for GPU userspace

### PR DESCRIPTION
**Pull request by Saviq**
Ref. https://forum.snapcraft.io/t/rfc-migrating-gnome-and-kde-snapcraft-extensions-to-gpu-2404-userspace-interface/39718

### CODE REVIEW

**Review by sergio-costas — APPROVED** [review]
It looks good. Moving these elements into its own snap seems sensible.

**Review by jssotomdz — APPROVED** [review]

**Comment by Saviq** [comment]
Dropped the temporary commit, desktop wrappers merged now.

**Comment by Saviq** [comment]
Hey, anything missing here?

**Review by seb128 — APPROVED** [review]
Seems fine to me and we probably want to land that before we start moving you snaps to core24 so let's merge now and see how it's working!

**Pull request merged**
