### PR TITLE
Fix thumbnailer

### PR DESCRIPTION
**Pull request by sergio-costas**
This patch fixes the thumbnails in cheese.

### CODE REVIEW

**Review by kenvandine — APPROVED** [review]
👍

**Comment by jbicha** [comment]
I think I rebuilt cheese against the updated gnome42-2204-sdk but I can't tell.

The thumbnails are not working in the cheese snap. Do you want me to open an issue somewhere for this? Where?

**Comment by seb128** [comment]
you shouldn't need a rebuild of cheese but did we get a gnome-42-2204 build including the change?

**Comment by kenvandine** [comment]
Not yet... But I'll kick that off

**Pull request merged**
