### PR TITLE
Add libadwaita to Gnome-42-2204

### PR DESCRIPTION
**Pull request by sergio-costas**
Fix https://github.com/ubuntu/gnome-sdk/issues/10

### CODE REVIEW

**Comment by 3v1n0** [comment]
We also need [this patch](https://salsa.debian.org/gnome-team/libadwaita/-/blob/ubuntu/master/debian/patches/ubuntu/style-manager-Support-Yaru-accent-colors.patch)  to be applied to work with yaru.

Let me know if it need a rebase

**Comment by sergio-costas** [comment]
Mmm... maybe that's why my SNAPs lack some icons...

**Comment by sergio-costas** [comment]
I'll add this patch.

**Comment by sergio-costas** [comment]
Added the patch.

**Comment by sergio-costas** [comment]
This should be ready to be merged...

**Pull request merged**
